// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpjqgcuywecqhkddncjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwanFnY3V5d2VjcWhrZGRuY2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDI2ODYsImV4cCI6MjA4ODcxODY4Nn0.YwDcaxS0DxP6rrfLjMe0ozrBGLJwQWF2znwmdCdlM9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});